name: Build and Analyze ESP32-C6 Firmware

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build Firmware
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install ESP-IDF and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git wget flex bison gperf python3 python3-pip cmake ninja-build ccache libffi-dev libssl-dev dfu-util
          git clone --recursive https://github.com/espressif/esp-idf.git
          cd esp-idf
          ./install.sh esp32c6
          echo "source $PWD/export.sh" >> $GITHUB_ENV

      - name: Build firmware
        run: |
          source esp-idf/export.sh
          idf.py build

      - name: Upload firmware
        uses: actions/upload-artifact@v3
        with:
          name: esp32c6-firmware
          path: build/*.bin

  static-analysis:
    name: Static Analysis (cppcheck)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install cppcheck
        run: sudo apt-get install -y cppcheck

      - name: Run cppcheck
        run: cppcheck --enable=all --inconclusive --std=c99 -I main main/
